### ISSUE TITLE
integrate with SAGTA authentication

### ISSUE THREAD

**Issue by gubuntu** [kartoza/SAGTA#24]
SAGTA wants to limit access to the downloader to users who are paid up SAGTA members, i.e. have an active account on https://sagta.org.za. They will need to see and use all SAGTA map projects in lizmap (but no admin access). 

public package = 'SAGTA Map Downloader Lite'
members' package = 'SAGTA Map Downloader Pro'

Detailed permissions

functionality | topo | ortho | hybrid
-|-|-|-
all | member | member | member
current view and download product | public | member | member 
annotations | member | member | member
magnetic declination | member | member | member
profile tool | member | member| member
any other new features | member | member | member

Some possible approaches:

- If Lizmap and sagta.org.za support OAuth, authenticate against it 
- create a 'secret' sagta user that logs in if the user logs in to sagta.org.za first and then goes to the map downloader, perhaps via a cookie with a token?

Talk to our devs for other ideas.

**Comment by lucernae** [comment]
@gubuntu just a wrap up from our discussion with @NyakudyaA @meomancer @dimasciput :

From the deployment/ops side, I want:
- Use approach that is decoupled with the programming language stack because the main website sagta.org.za and lizmap use different stack
- Recommended SSO-like implementation to make it easy for ops to deploy. Possible approach is to use OAuth or JWT token

From the development side currently we identify:
- Main sagta site use Django + Wagtail. OAuth server package is already available. But need to implement small package to retrieve the permission matrix via REST API preferrably. If using JWT, then approach is the same, but to get JWT Token for resources in lizmap. This part seems straightforward
- Lizmap uses PHP. We are unfamiliar with the current trend, but I think either @dimasciput and @meomancer have been working on PHP in the past.
- Lizmap currently don't have OAuth and JWT implemented, so either we need to make it, or confirm to 3Liz if this feature exists or is in the roadmap. For this part, it needs more time.

**Comment by gubuntu** [comment]
@NyakudyaA have you set up the folders as you propose above, on the staging site, so @dimasciput can set up and test auth accordingly?

**Comment by NyakudyaA** [comment]
> @NyakudyaA have you set up the folders as you propose above, on the staging site, so @dimasciput can set up and test auth accordingly?

Not yet, Will do this shortly so that he can test the auth

**Comment by NyakudyaA** [comment]
This has been set up but should I completely disable anonymous viewership for the satging site ?

**Comment by gubuntu** [comment]
How did it go today? If it's all done please post some screencasts here of it working and close

**Comment by dimasciput** [comment]
@gubuntu this is done and already tested and deployed.
